name: docker-image

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: run pacman -Syu --noconfirm
      run: docker run archlinux:base pacman -Syu --noconfirm
